---
- hosts: all
  become: yes
  tasks:
  - name: update the apt packages
    apt:
      update_cache: yes
  
# below are the settings for nodejs or appserver specific settings 
- hosts: Appserver
  become: yes
  vars:
    folder_path: /home/ansible/nodesetup
    template_path: /home/ansible/usecase_ansible
  tasks:
  - name: create a directory to place the shell file
  # create a directory(nodesetup) if it doesn't exist
  # installation steps are taken from https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04
    file:
      path: "{{ folder_path }}"
      state: directory
      mode: 0755
  #- name: change to the nodesetup directory

  - name: Download nodejs package setup
    command: curl -sL https://deb.nodesource.com/setup_6.x -o {{ folder_path }}/nodesource_setup.sh
  - name: Execute downlaoded nodesource_setup.sh
    shell: sudo bash {{ folder_path }}/nodesource_setup.sh
  - name: install nodejs package now
    apt:
      name: nodejs
      state: present
  - name: copy the sample nodejs code to check the applciaiton running on target node
    template:
      src: "templates/hello.js.j2"
      dest: "{{ folder_path }}/hello.js"
  - name: install pm2
    npm:
      name: pm2
      global: y
  - name: start node.js avi_application
    command: "pm2 start {{ folder_path }}/hello.js"

- hosts: Appserver
  become: yes
  vars:
    webserver_dns_name: "ec2-52-15-221-106.us-east-2.compute.amazonaws.com"
    appserver_ip: 172.31.39.65
  tasks:
  - name: install nginix
    apt:
      name: nginx
      status: present
  - name: copy default file
    template:
      src: "templates/default.j2"
      dest: "/etc/nginx/sites-available/default"
    notify:
      - restart Nginx
  handlers:
  - name: restart Nginx
    service:
      name: nginx
      state: restarted



    